name = "SpecialGraphs"
uuid = "3fe82f12-2b8d-5e30-b8ab-0037a6cca5e1"
authors = ["Mathieu Besançon <mathieu.besancon@gmail.com>"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1.1"
LightGraphs = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
